name: tests

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: npm
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: npm install
      - run: cd functions && npm install
      - name: Run ESLint
        run: npm run lint
        continue-on-error: false # Ensure the workflow fails if ESLint fails
      - name: Run Prettier
        run: npm run format:check
